[package]
name = "crypto-math"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
rand_core = "*"
stop-thread = "0.2.0"
[profile.dev]
opt-level = 3
debug = true

